project:
  type: website
  output-dir: docs

website:
  title: "WorldRegio"
  navbar:
    left:
      - href: index.qmd
        text: "Project"
      - href: author.qmd
        text: "Author"
      - links.qmd
      - posts.qmd
    right: 
      - icon: github # add icons as navbar buttons
        href: https://github.com/worldregio
        target: _blank
  page-footer:
    background: dark
    left: Copyright 2024, Claude Grasland
format:
  html:
    theme: 
      dark: solar
      light: minty
    css: styles.css
    toc: true



